-- 1. EXTENSIONS
create extension if not exists "uuid-ossp";
create extension if not exists "pgcrypto";

-- 1.5 MIGRATED USERS (DUMMY ACCOUNTS TO PRESERVE FOREIGN KEYS)
-- Inserting dummy user for the existing boat owner from the cloud database
-- User can later reset password or we can just link this boat to a real user later
insert into auth.users (
  id, instance_id, aud, role, email, encrypted_password, email_confirmed_at,
  recovery_sent_at, last_sign_in_at, raw_app_meta_data, raw_user_meta_data,
  created_at, updated_at, confirmation_token, email_change, email_change_token_new, recovery_token
)
values (
  'b0d3b92d-e05a-41cf-b90a-029c21c9d4fa',
  '00000000-0000-0000-0000-000000000000',
  'authenticated',
  'authenticated',
  'migrated_user@tts.local',
  crypt('temporary_password_123!', gen_salt('bf')),
  now(),
  null,
  now(),
  '{"provider":"email","providers":["email"]}',
  '{}',
  now(),
  now(),
  '',
  '',
  '',
  ''
) on conflict (id) do nothing;


-- 2. BOATS TABLE
create table if not exists boats (
  id uuid primary key default uuid_generate_v4(),
  user_id uuid references auth.users not null,
  name text not null,
  device_secret text not null,
  mac_address text,
  created_at timestamptz default now()
);

-- 3. TELEMETRY TABLE
create table if not exists telemetry (
  id bigint generated by default as identity primary key,
  boat_id uuid references boats(id) not null,
  created_at timestamptz default now(),
  
  -- Common Data
  voltage numeric,
  current numeric,
  power numeric,
  
  -- Battery Monitor
  soc numeric,
  consumed_ah numeric,
  remaining_mins integer,
  aux_voltage numeric,
  
  -- Solar Charger
  pv_power numeric,
  pv_voltage numeric,
  pv_current numeric,
  load_current numeric,
  load_state integer,
  device_state integer,
  yield_today numeric,
  efficiency numeric,
  temperature numeric,
  alarm integer,
  mac_address text,
  device_type integer,
  charge_state integer,
  total_yield numeric,
  max_pv_voltage numeric,
  max_pv_power numeric,
  min_battery_voltage numeric,
  max_battery_voltage numeric
);

-- 4. PERMISSIONS
GRANT ALL ON TABLE boats TO anon, authenticated, service_role;
GRANT ALL ON TABLE telemetry TO anon, authenticated, service_role;
GRANT ALL ON SEQUENCE telemetry_id_seq TO anon, authenticated, service_role;

-- 5. ENABLE RLS
alter table boats enable row level security;
alter table telemetry enable row level security;

-- 6. POLICIES FOR BOATS
drop policy if exists "Users can view their own boats" on boats;
create policy "Users can view their own boats" on boats for select using ( auth.uid() = user_id );

drop policy if exists "Users can insert their own boats" on boats;
create policy "Users can insert their own boats" on boats for insert with check ( auth.uid() = user_id );

-- 7. POLICIES FOR TELEMETRY
drop policy if exists "Users can view telemetry for their boats" on telemetry;
create policy "Users can view telemetry for their boats" on telemetry for select using ( 
    boat_id in (select id from boats where user_id = auth.uid())
);

drop policy if exists "Service role can insert telemetry" on telemetry;
create policy "Service role can insert telemetry" on telemetry for insert with check (true);

drop policy if exists "Anon role can insert telemetry" on telemetry;
create policy "Anon role can insert telemetry" on telemetry for insert to anon with check (true);

-- 8. REALTIME ENABLE
do $$
begin
  alter publication supabase_realtime add table telemetry;
exception when others then
  null;
end;
$$;

-- 9. INDEXES
create index if not exists telemetry_boat_id_idx on telemetry(boat_id);
create index if not exists telemetry_created_at_idx on telemetry(created_at desc);

-- 10. OPTIMIZATIONS & VIEWS
CREATE OR REPLACE VIEW latest_device_telemetry AS
SELECT DISTINCT ON (boat_id, mac_address) *
FROM telemetry
ORDER BY boat_id, mac_address, created_at DESC;

CREATE OR REPLACE FUNCTION get_daily_max_values(p_boat_id UUID) 
RETURNS TABLE (
  mac_address TEXT, 
  pmax NUMERIC, 
  vmax NUMERIC
) AS $$
BEGIN
  RETURN QUERY
  SELECT 
    t.mac_address::text,
    MAX(t.pv_power)::numeric as pmax,
    MAX(t.pv_voltage)::numeric as vmax
  FROM telemetry t
  WHERE t.boat_id = p_boat_id
    AND t.created_at >= date_trunc('day', CURRENT_DATE)
    AND t.device_type = 1
  GROUP BY t.mac_address;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 11. INGEST FUNCTION
CREATE OR REPLACE FUNCTION ingest_telemetry(payload jsonb)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_boat_id uuid;
  v_count int := 0;
  item jsonb;
BEGIN
  SELECT id INTO v_boat_id 
  FROM boats 
  WHERE id = (payload->>'boat_id')::uuid 
    AND device_secret = payload->>'device_secret';
    
  IF v_boat_id IS NULL THEN
    RETURN jsonb_build_object('success', false, 'error', 'Invalid boat_id or secret');
  END IF;

  FOR item IN SELECT * FROM jsonb_array_elements(payload->'data')
  LOOP
    IF item->>'mac_address' IS NOT NULL THEN
        INSERT INTO telemetry (
            boat_id,
            mac_address,
            voltage,
            current,
            temperature,
            alarm,
            device_type,
            soc,
            pv_power,
            pv_voltage,
            pv_current,
            load_current,
            device_state,
            yield_today,
            efficiency,
            consumed_ah,
            remaining_mins,
            aux_voltage,
            load_state
        ) VALUES (
            v_boat_id,
            item->>'mac_address',
            (item->>'voltage')::numeric,
            (item->>'current')::numeric,
            (item->>'temperature')::numeric,
            (item->>'alarm')::int,
            (item->>'device_type')::int,
            (item->>'soc')::numeric,
            (item->>'pv_power')::numeric,
            (item->>'pv_voltage')::numeric,
            (item->>'pv_current')::numeric,
            (item->>'load_current')::numeric,
            (item->>'device_state')::int,
            (item->>'yield_today')::numeric,
            (item->>'efficiency')::numeric,
            (item->>'consumed_ah')::numeric,
            (item->>'remaining_mins')::numeric,
            (item->>'aux_voltage')::numeric,
            (item->>'load_state')::int
        );
        v_count := v_count + 1;
    END IF;
  END LOOP;

  RETURN jsonb_build_object('success', true, 'inserted_count', v_count);
END;
$$;

NOTIFY pgrst, 'reload schema';
