# Veritabanı Şeması (PostgreSQL)

Bu dosya Supabase üzerinde çalışacak SQL komutlarını içerir.

```sql
-- 1. Kullanıcılar tablosu (Supabase Auth ile entegre)
-- Supabase 'auth.users' tablosunu otomatik yönetir, biz profil tablosu oluşturuyoruz.
create table public.profiles (
  id uuid references auth.users not null primary key,
  email text,
  full_name text,
  created_at timestamptz default now()
);

-- 2. Tekneler Tablosu
create table public.boats (
  id uuid default gen_random_uuid() primary key,
  created_at timestamptz default now(),
  name text not null,
  owner_id uuid references public.profiles(id) not null,
  device_secret text not null, -- Cihazın API'ye veri atarken kullanacağı basit şifre
  victron_mac_address text, -- Opsiyonel: Hangi cihazı dinleyeceğini sabitlemek için
  
  -- İzolasyon için Row Level Security (RLS)
  constraint owner_access unique(id, owner_id)
);

-- 3. Telemetri (Veri) Tablosu
create table public.telemetry (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(), -- Verinin sunucuya geliş zamanı
  measured_at timestamptz not null,     -- Verinin cihazda ölçüldüğü zaman
  boat_id uuid references public.boats(id) not null,
  
  -- Victron Verileri
  voltage numeric(5,2), -- Örn: 12.85
  current numeric(5,2), -- Örn: -5.40
  power numeric(7,2),   -- Örn: 120.50
  soc numeric(4,1),     -- Örn: 98.5
  temperature numeric(4,1),
  alarm_status int default 0
);

-- Indexler (Performans için kritik)
create index idx_telemetry_boat_time on public.telemetry(boat_id, measured_at desc);

-- 4. RLS Politikaları (Güvenlik)
alter table public.profiles enable row level security;
alter table public.boats enable row level security;
alter table public.telemetry enable row level security;

-- Kullanıcılar sadece kendi profillerini görebilir
create policy "Users can view own profile" on public.profiles
  for select using (auth.uid() = id);

-- Kullanıcılar sadece kendi teknelerini görebilir
create policy "Users can view own boats" on public.boats
  for select using (auth.uid() = owner_id);

-- Kullanıcılar sadece kendi teknelerinin verilerini görebilir
create policy "Users can view own telemetry" on public.telemetry
  for select using (
    exists (
      select 1 from public.boats
      where boats.id = telemetry.boat_id
      and boats.owner_id = auth.uid()
    )
  );

-- NOT: Telemetri ekleme (INSERT) işlemi Service Role (Backend API) tarafından yapılacağı için
-- son kullanıcıya INSERT izni vermiyoruz. Cihazlar API üzerinden yazar.
```
