-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- BOATS TABLE
create table if not exists boats (
  id uuid primary key default uuid_generate_v4(),
  user_id uuid references auth.users not null,
  name text not null,
  device_secret text not null,
  created_at timestamptz default now()
);

-- TELEMETRY TABLE
create table if not exists telemetry (
  id bigint generated by default as identity primary key,
  boat_id uuid references boats(id) not null,
  created_at timestamptz default now(),
  
  -- Common Data
  voltage numeric,
  current numeric,
  power numeric,
  
  -- Battery Monitor
  soc numeric,
  consumed_ah numeric,
  remaining_mins integer,
  aux_voltage numeric,
  
  -- Solar Charger
  pv_power numeric,
  pv_voltage numeric,
  pv_current numeric,
  load_current numeric,
  load_state integer,
  device_state integer,
  yield_today numeric,
  efficiency numeric,
  temperature numeric,
  alarm integer,
  mac_address text,
  device_type integer
);

-- PERMISSIONS (Önemli: API erişimi için)
GRANT ALL ON TABLE boats TO anon, authenticated, service_role;
GRANT ALL ON TABLE telemetry TO anon, authenticated, service_role;
GRANT ALL ON SEQUENCE telemetry_id_seq TO anon, authenticated, service_role;

-- ENABLE RLS
alter table boats enable row level security;
alter table telemetry enable row level security;

-- POLICIES FOR BOATS
drop policy if exists "Users can view their own boats" on boats;
create policy "Users can view their own boats" on boats for select using ( auth.uid() = user_id );

drop policy if exists "Users can insert their own boats" on boats;
create policy "Users can insert their own boats" on boats for insert with check ( auth.uid() = user_id );

-- POLICIES FOR TELEMETRY
drop policy if exists "Users can view telemetry for their boats" on telemetry;
create policy "Users can view telemetry for their boats" on telemetry for select using ( 
    boat_id in (select id from boats where user_id = auth.uid())
);

drop policy if exists "Service role can insert telemetry" on telemetry;
create policy "Service role can insert telemetry" on telemetry for insert with check (true);

-- REALTIME
-- 'supabase_realtime' yayınına tabloyu ekle (Eğer zaten ekliyse hata vermez veya ignore eder)
do $$
begin
  alter publication supabase_realtime add table telemetry;
exception when others then
  null;
end;
$$;

-- INDEXES
create index if not exists telemetry_boat_id_idx on telemetry(boat_id);
create index if not exists telemetry_created_at_idx on telemetry(created_at desc);

-- RELOAD SCHEMA CACHE
NOTIFY pgrst, 'reload schema';
