-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- BOATS TABLE
create table if not exists boats (
  id uuid primary key default uuid_generate_v4(),
  user_id uuid references auth.users not null,
  name text not null,
  device_secret text not null, -- Secret key for the ESP32 to authenticate or link
  created_at timestamptz default now()
);

-- TELEMETRY TABLE
create table if not exists telemetry (
  id bigint generated by default as identity primary key,
  boat_id uuid references boats(id) not null,
  created_at timestamptz default now(),
  
  -- Common Data
  voltage numeric,
  current numeric,
  power numeric,
  
  -- Battery Monitor
  soc numeric,
  consumed_ah numeric,
  remaining_mins integer,
  aux_voltage numeric, -- Starter Battery
  
  -- Solar Charger
  pv_power numeric,
  pv_voltage numeric,
  pv_current numeric,
  load_current numeric,
  load_state integer, -- Virtual Load Output
  device_state integer,
  yield_today numeric, -- Günlük Üretim (kWh)
  efficiency numeric, -- Verim (%)
  temperature numeric,
  alarm integer,
  mac_address text, -- To distinguish devices (MPPT vs Shunt)
  device_type integer -- 1: Solar, 2: Battery, 3: Inverter, etc.
);

-- ENABLE RLS
alter table boats enable row level security;
alter table telemetry enable row level security;

-- POLICIES FOR BOATS
-- Users can only see their own boats
create policy "Users can view their own boats"
  on boats for select
  using ( auth.uid() = user_id );

-- Users can insert their own boats
create policy "Users can insert their own boats"
  on boats for insert
  with check ( auth.uid() = user_id );

-- POLICIES FOR TELEMETRY
-- Users can view telemetry for their boats
create policy "Users can view telemetry for their boats"
  on telemetry for select
  using ( 
    boat_id in (
      select id from boats where user_id = auth.uid()
    )
  );

-- Allow insert via Service Role (or authenticated device if we add that logic later)
-- For now, we assume the backend/device uses a key that bypasses RLS or we add a policy:
-- create policy "Devices can insert telemetry" on telemetry for insert with check (true); 
-- BUT better to keep it secure. Default denies insert to public/anon.

-- REALTIME
-- Enable realtime for telemetry table
-- We assume 'supabase_realtime' publication exists (default in Supabase).
-- If not, uncomment: create publication supabase_realtime;
alter publication supabase_realtime add table telemetry;

-- INDEXES
create index if not exists telemetry_boat_id_idx on telemetry(boat_id);
create index if not exists telemetry_created_at_idx on telemetry(created_at desc);
