-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Update boats table to support MAC Address based registration
CREATE TABLE IF NOT EXISTS public.boats (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    name TEXT NOT NULL,
    mac_address TEXT UNIQUE,  -- Cihazın MAC Adresi (Benzersiz Kimlik)
    description TEXT,
    user_id UUID REFERENCES auth.users(id) -- Opsiyonel: Teknenin sahibi olan kullanıcı
);

-- Telemetry tablosunu Victron verileriyle güncelle
CREATE TABLE IF NOT EXISTS public.telemetry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    boat_id UUID REFERENCES public.boats(id) NOT NULL,
    
    -- Temel Veriler
    voltage NUMERIC,
    current NUMERIC,
    temperature NUMERIC,
    alarm INTEGER,
    device_type INTEGER, -- 1=Solar, 2=BMV, etc.
    
    -- Solar & Akü Detayları
    soc NUMERIC,           -- State of Charge (%)
    power NUMERIC,         -- Anlık Güç (W)
    pv_voltage NUMERIC,    -- Panel Voltajı
    pv_current NUMERIC,    -- Panel Akımı
    pv_power NUMERIC,      -- Panel Gücü (W)
    
    -- Yük Çıkışı
    load_current NUMERIC,  -- Yük Akımı
    load_state INTEGER,    -- Yük Durumu (0=Kapalı, 1=Açık)
    
    -- Durum Bilgileri
    device_state INTEGER,  -- Cihaz Durumu (Hata kodu vs.)
    charge_state TEXT,     -- Şarj Durumu: "Bulk", "Absorption", "Float", "Off"
    
    -- İstatistikler (Günlük/Toplam)
    yield_today NUMERIC,       -- Bugün Üretilen Enerji (kWh)
    total_yield NUMERIC,       -- Toplam Üretilen Enerji (kWh - Lifetime)
    max_pv_voltage NUMERIC,    -- Günlük Max Panel Voltajı
    max_pv_power NUMERIC,      -- Günlük Max Panel Gücü
    min_battery_voltage NUMERIC, -- Günlük Min Akü Voltajı
    max_battery_voltage NUMERIC, -- Günlük Max Akü Voltajı
    consumed_ah NUMERIC,       -- Tüketilen Ah
    remaining_mins NUMERIC,    -- Kalan Süre (Dakika)
    efficiency NUMERIC,        -- Verim (%)
    aux_voltage NUMERIC        -- Yardımcı Akü Voltajı (Starter Battery)
);

-- RLS Politikaları (Güvenlik)
ALTER TABLE public.boats ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.telemetry ENABLE ROW LEVEL SECURITY;

-- Herkese okuma izni ver (Şimdilik test için)
CREATE POLICY "Allow public read access" ON public.boats FOR SELECT USING (true);
CREATE POLICY "Allow public insert access" ON public.boats FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public read access" ON public.telemetry FOR SELECT USING (true);
CREATE POLICY "Allow public insert access" ON public.telemetry FOR INSERT WITH CHECK (true);

-- RPC Fonksiyonu: Telemetri Verisini İşle (Otomatik Tekne Kaydı ile)
CREATE OR REPLACE FUNCTION public.ingest_telemetry(payload JSONB)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    measurement JSONB;
    boat_uuid UUID;
    _mac_address TEXT;
    _boat_name TEXT;
    result_ids BIGINT[];
BEGIN
    -- Gelen JSON array içindeki her ölçümü işle
    FOR measurement IN SELECT * FROM jsonb_array_elements(payload)
    LOOP
        _mac_address := measurement->>'mac_address';
        _boat_name := COALESCE(measurement->>'boat_name', 'Unknown Boat');

        -- 1. Tekneyi Bul veya Oluştur (MAC Adresine Göre)
        IF _mac_address IS NOT NULL THEN
            SELECT id INTO boat_uuid FROM public.boats WHERE mac_address = _mac_address;
            
            IF boat_uuid IS NULL THEN
                INSERT INTO public.boats (name, mac_address)
                VALUES (_boat_name, _mac_address)
                RETURNING id INTO boat_uuid;
            END IF;
        ELSE
            -- MAC adresi yoksa, boat_id ile dene (Eski uyumluluk)
            boat_uuid := (measurement->>'boat_id')::UUID;
        END IF;

        -- 2. Veriyi Telemetry Tablosuna Yaz
        IF boat_uuid IS NOT NULL THEN
            INSERT INTO public.telemetry (
                boat_id,
                voltage, current, temperature, alarm, device_type,
                soc, power, pv_voltage, pv_current, pv_power,
                load_current, load_state, device_state, charge_state,
                yield_today, total_yield, max_pv_voltage, max_pv_power,
                min_battery_voltage, max_battery_voltage,
                consumed_ah, remaining_mins, efficiency, aux_voltage
            )
            VALUES (
                boat_uuid,
                (measurement->>'voltage')::NUMERIC,
                (measurement->>'current')::NUMERIC,
                (measurement->>'temperature')::NUMERIC,
                (measurement->>'alarm')::INTEGER,
                (measurement->>'device_type')::INTEGER,
                (measurement->>'soc')::NUMERIC,
                (measurement->>'power')::NUMERIC,
                (measurement->>'pv_voltage')::NUMERIC,
                (measurement->>'pv_current')::NUMERIC,
                (measurement->>'pv_power')::NUMERIC,
                (measurement->>'load_current')::NUMERIC,
                (measurement->>'load_state')::INTEGER,
                (measurement->>'device_state')::INTEGER,
                (measurement->>'charge_state'),
                (measurement->>'yield_today')::NUMERIC,
                (measurement->>'total_yield')::NUMERIC,
                (measurement->>'max_pv_voltage')::NUMERIC,
                (measurement->>'max_pv_power')::NUMERIC,
                (measurement->>'min_battery_voltage')::NUMERIC,
                (measurement->>'max_battery_voltage')::NUMERIC,
                (measurement->>'consumed_ah')::NUMERIC,
                (measurement->>'remaining_mins')::NUMERIC,
                (measurement->>'efficiency')::NUMERIC,
                (measurement->>'aux_voltage')::NUMERIC
            );
        END IF;
    END LOOP;

    RETURN jsonb_build_object('status', 'success', 'message', 'Telemetry ingested');
END;
$$;
