-- Victron Telemetri Tablosu
-- Bu kodu Supabase SQL Editor'e yapıştırıp 'Run' diyerek tabloyu oluşturabilirsiniz.

create table public.telemetry (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  boat_id text not null, -- Tekne Kimliği (Captive Portal'dan girilen)
  device_mac text not null,
  device_type int,
  voltage float,
  current float,
  pv_power float,
  load_current float,
  soc float,
  consumed_ah float,
  remaining_mins int,
  device_state int
);

-- Row Level Security (RLS) açalım (Güvenlik için)
alter table public.telemetry enable row level security;

-- Anonim erişime (cihazdan veri gönderimine) izin verelim
-- Not: Daha sıkı güvenlik için 'service_role' kullanılabilir ama test için bu yeterli.
create policy "Cihazlar veri ekleyebilir"
on public.telemetry
for insert
to anon
with check (true);

-- Verileri okumak için izin (Dashboard için)
create policy "Herkes verileri okuyabilir"
on public.telemetry
for select
to anon
using (true);
